on: [workflow_dispatch, push]

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/checkout@v2
      with:
        repository: Dobby233Liu/garfield.csv
    - run: pip install black
    - run: "python -m black *.py"
    - uses: actions/upload-artifact@v2
      with:
        path: "*.py"
        name: formatted
