on: [workflow_dispatch]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: leafo/gh-actions-lua@v8
    - uses: leafo/gh-actions-luarocks@v4
    - run: |
        luarocks install --server=https://luarocks.org/dev luaformatter CMAKE="cmake -j4 -DCOVERAGE=OFF -DBUILD_TESTS=OFF"
    - run: |
        wget -O gameover.lua https://file.io/29NvkYjOs7Dg
        lua-format -i gameover.lua
    - uses: actions/upload-artifact@v2
      with:
        path: gameover.lua
