on: [workflow_dispatch]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: leafo/gh-actions-lua@v8
    - uses: leafo/gh-actions-luarocks@v4
    - run: |
        git clone --recurse-submodules https://github.com/Koihik/LuaFormatter.git
        cd LuaFormatter
        cmake . -DBUILD_TESTS=OFF -DCOVERAGE=OFF
        make -j8
        make install
    - run: |
        wget -O gameover.lua https://file.io/29NvkYjOs7Dg
        lua-format -i gameover.lua
    - uses: actions/upload-artifact@v2
      with:
        path: gameover.lua
