on: [workflow_dispatch]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: leafo/gh-actions-lua@v8
    - uses: leafo/gh-actions-luarocks@v4
    - run: |
        luarocks install --server=https://luarocks.org/dev luaformatter
        wget https://file.io/w1cJsMw2LV9l
        lua-format gameover.lua
    - uses: actions/upload-artifact@v2
      with:
        path: gameover.lua
