on: [push, workflow_dispatch]
jobs:
  aa:
    runs-on: windows-latest
    steps:
      - run: |
          curl -o a.tar.xz -L -s "https://osdn.net/projects/mingw/downloads/72217/gcc-core-9.2.0-3-mingw32-bin.tar.xz"
          curl -o aa.tar.xz -L -s "https://osdn.net/projects/mingw/downloads/72211/gcc-c++-9.2.0-3-mingw32-bin.tar.xz"
          dir a.tar.xz
        shell: cmd
        working-directory: ${{ runner.temp }}
